import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# The CSV generated by Rust main()
# Columns: time,q_w,q_x,q_y,q_z,w_x,w_y,w_z,rw1,rw2,rw3
df = pd.read_csv("sim_output.csv")

t = df["time"].to_numpy()
q_w = df["q_w"].to_numpy()
q_x = df["q_x"].to_numpy()
q_y = df["q_y"].to_numpy()
q_z = df["q_z"].to_numpy()
w_x = df["w_x"].to_numpy()
w_y = df["w_y"].to_numpy()
w_z = df["w_z"].to_numpy()
rw1 = df["rw1"].to_numpy()
rw2 = df["rw2"].to_numpy()
rw3 = df["rw3"].to_numpy()

def quat_conjugate(q):
    """Return conjugate of quaternion [w, x, y, z]."""
    return np.array([q[0], -q[1], -q[2], -q[3]])

def quat_multiply(q1, q2):
    """Quaternion Hamilton product."""
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    return np.array([
        w1*w2 - x1*x2 - y1*y2 - z1*z2,
        w1*x2 + x1*w2 + y1*z2 - z1*y2,
        w1*y2 - x1*z2 + y1*w2 + z1*x2,
        w1*z2 + x1*y2 - y1*x2 + z1*w2
    ])

def quaternion_error(q_current, q_target):
    """Calculate error quaternion: q_err = q_target * conj(q_current)."""
    return quat_multiply(q_current, quat_conjugate(q_target))

# Compute Attitude Error (vector part)
q_target = np.array([1.0, 0.0, 0.0, 0.0])
q_err_history = np.zeros((len(t), 3))

for i in range(len(t)):
    q_curr = np.array([q_w[i], q_x[i], q_y[i], q_z[i]])
    q_err = quaternion_error(q_curr, q_target)
    q_err_history[i, :] = quaternion_error(q_curr, q_target)[1:]

# Plotting (aligned with the Python nanosats.pdf reference)
plt.style.use("seaborn-v0_8-darkgrid")
fig, axs = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

# (1) Attitude Error
axs[0].plot(t, q_err_history[:, 0], label="Error q_x")
axs[0].plot(t, q_err_history[:, 1], label="Error q_y")
axs[0].plot(t, q_err_history[:, 2], label="Error q_z")
axs[0].set_ylabel("Attitude Error")
axs[0].set_title("Nanosatellite Attitude Control Simulation")
axs[0].legend()
axs[0].grid(True)

# (2) Angular Velocity 
axs[1].plot(t, w_x, label="w_x")
axs[1].plot(t, w_y, label="w_y")
axs[1].plot(t, w_z, label="w_z")
axs[1].set_ylabel("Angular Velocity [rad/s]")
axs[1].legend()
axs[1].grid(True)

# (3)Reaction Wheel Speeds
axs[2].plot(t, rw1, label="RW 1")
axs[2].plot(t, rw2, label="RW 2")
axs[2].plot(t, rw3, label="RW 3")
axs[2].set_xlabel("Time [s]")
axs[2].set_ylabel("Reaction Wheel Speed [rad/s]")
axs[2].legend()
axs[2].grid(True)

plt.tight_layout()
plt.show()
